### ISSUE TITLE
Question about 2B

### ISSUE THREAD

**Issue by Martin-Andersen** [wardviaene/terraform-course#2]
This is about lesson 2B

When I run "terraform apply" the instance are created and the powershell scripts runs without any errors.
but the fileupload are failing:

provisioner "file" {
    source = "test.txt"
    destination = "C:/test.txt"
  } 

* aws_instance.win-example: 1 error(s) occurred:
* unknown error Post http://54.229.229.22:5985/wsman: dial tcp 54.229.229.22:5985: getsockopt: operation timed out

But its not a timeout problem, have tried to increase timeout but it's not helping.
Is there a way that I can debug the problem? is it better to use packer? In the end I am going to create a win server with sitecore on it.

All development are made on OS X or ubuntu

**Comment by wardviaene** [comment]
You need to make sure that you have a security group that allows access to port 5985, otherwise you'll indeed get a timeout. You might setup one manually just to test the demo, but it's better to add a security_group resource in for example securitygroups.tf. See other demos how you do that.

Also sorry for the late answer. If you're following the course on Udemy, use the Q&A section there to get a reply much sooner.

**Comment by Martin-Andersen** [comment]
Thanks that solved the problem
